- name: Check /proc/sys/net/ipv4/ip_forward
  ansible.builtin.command: cat /proc/sys/net/ipv4/ip_forward
  register: ip_forward

- name: Enable IPv4 packet forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#net.ipv4.ip_forward=1'
    line: 'net.ipv4.ip_forward=1'
  when: ip_forward.stdout != '1'

- name: Apply sysctl changes
  ansible.builtin.command: sysctl -p
  when: ip_forward.stdout != '1'

- name: Install WireGuard
  ansible.builtin.apt:
    name: wireguard
    state: latest
    cache_valid_time: 3600

- name: Copy over config
  ansible.builtin.template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    mode: "600"
  register: config

- name: Reload WireGuard interface
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: true
  when: config.changed
