- name: Install updates
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
    autoclean: yes

- name: Ensure needrestart is installed
  ansible.builtin.apt:
    name: needrestart
    state: latest

- name: Run needrestart
  ansible.builtin.shell: needrestart -r a # Auto restart any services that require a restart

- name: Check for pending reboot
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required.stat.exists

- name: Sleep for 10 minutes
  ansible.builtin.pause:
    minutes: 10
