- name: Install updates
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
    autoclean: yes

- name: Ensure needrestart is installed
  ansible.builtin.apt:
    name: needrestart
    state: latest

- name: Run needrestart
  ansible.builtin.shell: needrestart -r a # Auto restart any services that require a restart

- name: Check for pending reboot
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

# https://github.com/liske/needrestart/blob/master/README.batch.md
# NEEDRESTART-KSTA: 1
# 0: unknown or failed to detect
# 1: no pending upgrade
# 2: ABI compatible upgrade pending
# 3: version upgrade pending
- name: Check for pending reboot due to kernel change
  ansible.builtin.shell: needrestart -bk | grep "KSTA" | cut -d" " -f2
  register: reboot_required_kernel

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists or (reboot_required_kernel.stdout | int) != 1

- name: Sleep for 1 hour
  ansible.builtin.pause:
    minutes: 60
