{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "seq-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "seq-secrets",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "immutable": true
    },
    "encryptedData": {
      "SEQ_API_KEY": "AgCDC5DhXgqF4NXv8ZoUF3r/Xw6voZuHplo/ppJTk7wjXMX6VPgFkfFdocK+kpwaqBWiO5yeQgrPRZewBeM+Q4XunhDTa6vRWQDlmmKNZVCxolxN6k0jD31r2H5iDH1cBweEhiwTlw6RCwOcfo0Jry/ZQvJIxU+NsyXmVrUdpQMFJqGW/Rwz9ncCZ511+8maZkISsgPivi9IQg+QC8ypZnXBfTJ8oSTDpzULNF4gUkBBpqWJwMN49lToVKcOe/uL1Hw/SEUIj6gcVnHBme+J/7tIX7ZeH8hmBaS5nkEwJcBk0hjiCOsn9yZNO3nZBdzryl+9QW1TtGEbEwd6ha/DOQRv1WcK9ExvUWEYFRXbqYo1eMjLDg+jeAnr4GVwJh+g6Nr06si7eah8gfvfa/IqJZkLZtX1tg3TXcuS8vnvmxJRLBskpTx6dw0bBxCh9de7MyM2n22+gyqMQQrbhQQBIQMdjujRlFubqGfwkYimY7tN0lhF03ufZ7EmqQBZntQJ+unnj/2+SDTh/qqSh1KsLrTwz2c8bX4lGiaI40nfjC7o52HyY7U+yGCdrrI6XSnimZu0r4semyY9PDTk5iKDw0C++SfqGREWy+Mi9WWk9RJvyXJ9zjRtNyQwRZe4iHhDQqgi0HoNsvUVr4strAd1mw9DMGrojPv5zSlAQjtpiNgxl518EKwNde/EesNo/7x+9uLAqzB+jTvNqz506RGRCRmHveIISQ=="
    }
  }
}
