{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "frigate-basic-auth",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "frigate-basic-auth",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "immutable": true
    },
    "encryptedData": {
      "auth": "AgAIQFa+XbEQYD/LpFFAb/KnPv6DJS/QrzTtXoolHyM4PKqYCoyfVe1pCB85nOmw3nAGlZJ3WbOC/IULLehdADCOTgYozpvTG4QMAoKi88XjL0kOrd1s8dtAnWTqJWUHcdEYq7xZJUvFT8kBQHW9GRwUaoctrKywgI6Ag4Klob9fLboyZAfTIKAyoo8+lgz8+Zr3Q7y65qp6nLF4GlO7HKikRSGWasA8DVKEzA/3PLvMVLAgKWTW4bYDmV8dqkqZdSCKrCUUG/aWxlcUugMIPYFqRKPVgpKIpPOEVFhcGQWGoAnVx6O/ml6XWGgWkfse+LMC752B5/LezD+Ebh6uUmD6kLO6nvuT+gAwqt9IBYiao3xB4BRBYkiCjZ1TsOPdd3QUt/gY7bOlUOg0W/RilQtKAgKA3wLO6qnxLjFiSuI4pccsbdk4E5R7gXm5Z4sczZtH+ZKfpbelxHrAGxPkoL+uxQjZkqY1bEnA+liJvKX+M8EaevUBoDpZuS5l5teWv9r+3ZcpndX3PDRqbuVQ1onlUI/KsDDqol8Xvj7FBklfC6iioelk2iAdOmAMohzsLzAdDo8F7ARQv7UX5ai50SDYBzBTa9GXFhXlvQwTXAhFGt+vKu1u+YJ8TutxyLuKMSATlFxfB/wRnE4ZHLB+Tkeoc0khQJHuRHDiomBvyDY/b32gH5SsBxJC8dAYXKtFl9vOR40Ft6lLghr5rOwtLoHXRIqx70nX6DwOsA3F9+RUJoJYuITMc4dkyYi1tg=="
    }
  }
}
