name: "Ansible - Garage Switch"

on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - ansible/**
      - .forgejo/workflows/ansible-garage-switch.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  ansible:
    name: "Ansible Run"
    runs-on: forgejo-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run playbook
        run: |
          cd ansible
          echo ${{ secrets.ANSIBLE_VAULT_KEY }} >> vault-pass
          export ANSIBLE_FORCE_COLOR=1
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i hosts --vault-password-file vault-pass playbooks/ansible-garage-switch.yml

      - name: Cleanup the vault secret, key and playbook
        if: always()
        run: |
          cd ansible
          rm -f vault-pass
