- name: Create sysctl config to disable IPv6
  ansible.builtin.copy:
    dest: /etc/sysctl.d/disable-ipv6.conf
    content: |
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
    owner: root
    group: root
    mode: '0644'

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system
