- name: Create Traefik directory
  ansible.builtin.file:
    path: "{{ DOCKER_VOLUMES_ROOT }}/traefik"
    state: directory
    mode: "770"

- name: Create LetsEncrypt directory
  ansible.builtin.file:
    path: "{{ DOCKER_VOLUMES_ROOT }}/traefik/letsencrypt"
    state: directory
    recurse: yes
    mode: "600" # Required for Traefik to work

- name: Create Traefik proxy network
  community.docker.docker_network:
    name: proxy

- name: Copy over docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ DOCKER_VOLUMES_ROOT }}/traefik/docker-compose.yml"
    mode: "770"

- name: Start compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ DOCKER_VOLUMES_ROOT }}/traefik"
    project_name: traefik

- name: Cleanup compose file
  ansible.builtin.file:
    path: "{{ DOCKER_VOLUMES_ROOT }}/traefik/docker-compose.yml"
    state: absent
