apiVersion: v1
kind: Secret
immutable: true
metadata:
  name: frigate-secrets
  namespace: default
type: Opaque
stringData:
  FRIGATE_C1_PASS: "xxx"
  FRIGATE_C2_PASS: "xxx"
  FRIGATE_C3_PASS: "xxx"
  FRIGATE_C4_PASS: "xxx"
