apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-configmap
  labels:
    app: filebrowser
data:
  .filebrowser.json: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/db/filebrowser.db",
      "root": "/srv"
    }
