apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-script-configmap
data:
  backup.sh: |
    #!/bin/bash

    DT=$(date "+%Y-%m-%d--%H-%M")

    echo "Starting backup at $DT"
    mariadb-dump -h zabbix-db \
    -uzabbix \
    -pzabbix \
    --single-transaction \
    --quick \
    --compress \
    --all-databases \
    > /backups/zabbix-mariadb-backup-$DT.sql

    if [ $? -ne 0 ]; then
      echo "Backup failed"
      echo 1 > /backups/last-exit-code.log
      exit 1
    fi

    echo "Compressing backup"
    gzip /backups/zabbix-mariadb-backup-$DT.sql

    if [ $? -ne 0 ]; then
      echo "Compression failed"
      echo 1 > /backups/last-exit-code.log
      exit 1
    fi

    echo "Deleting backups older than 3 days"
    BACKUP_COUNT=$(ls /backups | wc -l)
    echo "There are $BACKUP_COUNT backups"
    if [ $BACKUP_COUNT -gt 3 ]
    then
        echo "Deleting *.gz backups older than 3 days"
        find /backups -mtime +3 -name "*.gz" -delete
        echo "Backup deletion complete"
    fi

    echo "Backup complete at $(date "+%Y-%m-%d--%H-%M")"
    echo 0 > /backups/last-exit-code.log
    exit 0
---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup-cronjob
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            zabbixdb: allowed
          volumes:
          - name: backups
            nfs:
              path: /mnt/ssd/k8s/zabbix/zabbix-db/backups
              server: 10.10.3.2
          - name: scripts
            configMap:
              name: backup-script-configmap

          containers:
          - name: mariadb-backup
            image: mariadb:11.5
            securityContext:
              runAsUser: 1000
            command:
            - "/bin/bash"
            - "/scripts/backup.sh"
            volumeMounts:
            - name: backups
              mountPath: /backups
            - name: scripts
              mountPath: /scripts

          restartPolicy: OnFailure
