apiVersion: v1
kind: ServiceAccount
metadata:
  name: zabbix-readonly

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zabbix-readonly
rules:
- nonResourceURLs:
  - "/metrics"
  - "/metrics/cadvisor"
  - "/version"
  - "/healthz"
  - "/readyz"
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - nodes/metrics
  - nodes/spec
  - nodes/proxy
  - nodes/stats
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - services
  - componentstatuses
  - nodes
  - endpoints
  - events
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list"]
- apiGroups: ["extensions"]
  resources:
  - deployments
  - daemonsets
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  - daemonsets
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zabbix-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zabbix-readonly
subjects:
- kind: ServiceAccount
  name: zabbix-readonly
  namespace: default
