apiVersion: v1
kind: Secret
immutable: true
metadata:
  name: gluetun-secrets
  namespace: default
type: Opaque
stringData:
  wireguard-private-key: "key"
  wireguard-addresses: "address"

---

apiVersion: v1
kind: Secret
immutable: true
metadata:
  name: transmission-secrets
  namespace: default
type: Opaque
stringData:
  transmission-password: "pass"
