- name: Ensure curl is installed
  ansible.builtin.apt:
    name: curl
    state: latest
    cache_valid_time: 3600

- name: Ensure /opt/disk-watchdog directory exists with correct permissions
  ansible.builtin.file:
    path: /opt/disk-watchdog
    state: directory
    mode: "700"

- name: Copy disk-watchdog.sh to /opt/disk-watchdog
  ansible.builtin.template:
    src: disk-watchdog.sh.j2
    dest: /opt/disk-watchdog/disk-watchdog.sh
    mode: "700"
  notify: Ensure disk-watchdog service is enabled and started

- name: Create systemd service file for disk-watchdog
  ansible.builtin.template:
    src: disk-watchdog.service.j2
    dest: /etc/systemd/system/disk-watchdog.service
    owner: root
    group: root
    mode: "644"
  notify: Ensure disk-watchdog service is enabled and started
