- name: Copy over docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "/mnt/ssd/docker-compose.yml"
    mode: "770"

- name: Start compose stack
  community.docker.docker_compose_v2:
    project_src: "/mnt/ssd"
    project_name: zabbix-agent

- name: Cleanup compose file
  ansible.builtin.file:
    path: "/mnt/ssd/docker-compose.yml"
    state: absent
