- name: Create Syncthing directory
  file:
    path: /opt/dockervolumes/syncthing/config
    state: directory
    mode: '770'
    recurse: true

- name: Copy over docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/dockervolumes/syncthing/docker-compose.yml
    mode: 0770

- name: Start compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/dockervolumes/syncthing
    project_name: syncthing
