{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "gluetun-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "gluetun-secrets",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "immutable": true
    },
    "encryptedData": {
      "wireguard-addresses": "AgAxbZNvYrboWazku0SEqossiublMWDT2qx+C38lAv8fX4AfQpCLMAcOjBXyN66w7mQjlYiRHLWm1AfgxXIMfSpZXC3dP4YUroHhkYvYHZRf2aS6Yd79DW1E4LaN9rSMg7l9C6KLseD0M127mIdJMNz3ejOb1xtTKZnAkXP/nAMFwCNgaY6d95BFMR4WdYIKXVktc7cUZtOfeodXxRE/uytbyMqGwRqj9hRn22NOjykUePwQGQpIoC3jHJdSuqF9Xq32Dtjrwc04pwK56qsQRWrgeMwmO9Kv+c0gdH0/rng8GhFkuFffAEw8gcCvu+Iu8TKwoKV8+x5GR2gD/TMX4O26cnU4+HsnhzeLBNpkhP7/q2CtsYw16C6hAVtG3HtoUtF3Z5t7wcvv8n756ll6npY/o3gre8pA3N3RwWJP1Jr8lrqqPxRvypol8Oghpl68P1IHAc4RChBIYvRN/BTAA/h1MB07IDZ7omRelzemUjh/bYRo8DXhybBJeMHllYS2HR2dAuUQ8R9GRaxx66CQRKsstkLkNEFvYYSeW9sD+N06fSZxPuKyelrFfJ+5rOG3+TvSeWsrDvfUH/+41o6TWja4wxi5uUBbsrN9GhiMgavJlOnZXy52FI8AuM6qVMmDkzap19cjMFbJU8xjRrrAnPGme9nJvQxbK1xy/xtSXDM2ip7ff9OUyc233e8pBZCG+XkB20AzPtYJKW4nUcXTs3g=",
      "wireguard-private-key": "AgDCpPdHjjDmBg7A/t3U/JzZUhU4f2de3iBn6tlOt+JLm3OtV87lNP4n/weB/oheTy613CWixi1IPAGiO53foBxxA+/GQZ7/98icNReS9oc+cPfL+IsOV4ltoqTzwfPmx6wOjcxajBh/b7svwUHdBxOxSGAncDl8HEcyMCKLDZ9XP/Q02X9oLXQkfIE6VBrkiK9aMAJzZ6y2Hf4i9R6ydRzYNLylVS5FlwOxKMNQLdnknNohtc76FZgsDcjAKPe4yDDrvOJdPBmXsV0ubooVCnCiaOPiUFR8F9urI+BwZStklmXlvusMMU2dXbiN3TPkJ+G/C+4FETM0fGxL36FkorkhhDEXHZHqnEmO2CukLhQVOpBjoWfBSkkPLrSSICJbm9kHRlf2Dtvq5kHXXLEv1wH5g7UUjSdh4gPJ7a0w2dazIg2E7ibyOLooh0XBLlM+ZXsFRIbgP0c9VIDuH6v1CO/g61V4GxSr6Kq3ejmdppKWLcQqn5RRXXTXYGtUJiBR8hhDpdey2ICFRUIE0PbLXUJT4WZCYAUq7TMWszOJTc5Z7J0MH39DoTUJSiuAcQ+2H1Txcx4IjCbd4JsAXFP+5mjgLeOrXxg3Nm8xkt+PuoLm8KMEElrDpgZwlNb5EaY/MMUDmnjnx2W/6wnr5PoUcMNjgs65uspxoa/n1zcAN9orUN/gVqfM2As46nDqCJRPCC2P1eKPFdk6C+AJqIj1S87+wTAu8MfNUQpq1j52BBnm32DYwHEGGj4/CHUb/w=="
    }
  }
}
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "transmission-secrets",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "transmission-secrets",
        "namespace": "default",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "immutable": true
    },
    "encryptedData": {
      "transmission-password": "AgAd8dmGDOwScSBOoaGRPMU/dEx2nCPPkSv3q4OZMl2J6E/a6MwQtJqr+qtNSG3ztFaYvn+e7dbtxoIVTQQ+fhgA6Jaxh28jwz/S6i9R+MYth9m1nAsxGuQVzdOraJ5nV6SYIl8owvodlsjZYBwZtMvhmCyvVYu9DMzuvDgkfA+D3hl7jWaVsuH8RSzPPTljRE1ut+6WoephSRMX0xq2YwFxF1uHTC4AH2c6AW6zZ90jAIcdC8jBtvZAhntfCT6adZI2hrMyPssvqxxH8WPHANaNqxNFajyvykmn++IdMM2xu5F8PmDRejKawnRFWIQ5N0vxDiVwHJ8QwNhz34mlQ1d0dLP37LXDol9Sco4FupfKQQDR75aC8e3zNtuRE8t03bAY1JAE+SI8LQKAkUYEZERUhVs5cu3i2CC6dIT6rK8Z4DLy2lEdcfVTZfdVtjthE7ynMnC/T7dr06nviHbMgMV1CdnXLTqwHl3AEbt5HCuqDdCJCr81Ct2OdC776CwAGP4V/ypMQDhsQ60UFMEg8KF0M0oYBnsFyaGPFALWXq+7g/RCiUBVfKqhSiTRIRjzcjt4+YyWjpmqR494lEs0cflZu3gnp3rjJI0QjQvKpaD+syCf/ZagQzO5SUofsGLYd6sWaB7IX5dv3zaXZTX6MUzQ+JiIE9+uMFLDsdHZoQZ17iwTpzdjIGy7K+hyfO1ibmBae1iEaWpxpDeeplsiVqiIPdlXdg=="
    }
  }
}
