{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token-secret",
    "namespace": "cert-manager",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token-secret",
        "namespace": "cert-manager",
        "creationTimestamp": null
      },
      "type": "Opaque",
      "immutable": true
    },
    "encryptedData": {
      "api-token": "AgB2fdh7kywhunVw/jDx+NPKMfDrVVVBVFGAyiQUajxb+3f31ALfAu9ih998/1ZDnw99KHEOfeINqM8sb+jZkM87uO/rOA5J2RdRSefYag7feD/9uJRFY/9n8foCvyc+mdghHNqKSqfHau6QU8NL+1kF1w2lDG2Jr+fOt98ODvFeCDWI+nqXcXCKa8HR+/U0Bbjlug6QzKGfuab2NhZQCmthXEqtm8DCmoNJ13s7xeYp6JNzAotIsAq9Pe4x7LvEXEmZD2tY5hVzTW7+K8YYBWN6yLjhmbPVu41AuW3ar5wQJyVW2uJC2RSVUXTEnxW9805CSv6uM5xNDkV8Iw7IZbVSE1fdPEbynN2rvnLn3SZLPTx3uYS7ZWrBqjsn/GVDgdw9fw1AePuwSkUOTU0af1o63uwsydu1UWOrXdlPjXwvvt/TQIZop38lhYaIFRcMBwVa+h9G92YAkq1Noqq+sBZ9iuSiQQSEfswhj21WJuhp2ZSvMzmg8gdzJ+6xFkzcEmkJIj204rUMlaFwHgXfw1D9ch0WRh4CGqLcBcWt70reGRjnLMxxSUoaS+fwWS39gQpUlNQta5xzG2x7xfQa3k/8ex+Yj0D1Cd6JvWZJ68vR+AlUDJdjMi4eUf0K+1jXu11qA/aSRM35eeqOzahywGyLINt8Gn6QfbWzzJzmySKim1Nq7QLsUPz7tMOvi2O7xW4rtGv9jH2Y7oFAEhR3S0B4c0xL5/dk7+7iNcilrHyen4J6kqBg1hPy"
    }
  }
}
