apiVersion: v1
kind: Secret
immutable: true
metadata:
  name: longhorn-basic-auth
  namespace: longhorn-system
type: Opaque
data:
  auth: "YWRtaW46JGFwcjEkMFNIdUxRMmMkYmJzTXBLdDNPRGNWeTBLVnVhWGdZMAo="
  # Must be in base64
  # Run the below to generate the string
  # echo '3hbpgYNXT1LQloZa2y2i' | htpasswd -ic auth-temp-file admin && cat auth-temp-file && echo "$(cat auth-temp-file)" | base64 && rm -f auth-temp-file
