- name: Create Watchtower directory
  file:
    path: /opt/dockervolumes/watchtower
    state: directory
    mode: '770'
    recurse: true

- name: Copy over docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/dockervolumes/watchtower/docker-compose.yml
    mode: '770'

- name: Start compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/dockervolumes/watchtower
    project_name: watchtower
