apiVersion: v1
kind: ServiceAccount
metadata:
  name: seq-fluent-bit

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seq-fluent-bit
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: seq-fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: seq-fluent-bit
subjects:
- kind: ServiceAccount
  name: seq-fluent-bit
  namespace: default
