- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    state: latest
    cache_valid_time: 3600

- name: Configure auto patching
  copy:
    src: 50-unattended-upgrades
    dest: /etc/apt/apt.conf.d/50-unattended-upgrades
