name: "Ansible - pipeline-runner"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - ansible/**
      - .github/workflows/ansible-pipeline-runner.yml

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  ansible:
    name: "Ansible Run"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo vault secret to file (ugh)
        run: |
          cd ansible
          echo ${{ secrets.ANSIBLE_VAULT_KEY }} >> vault-pass

      - name: Run playbook
        run: |
          cd ansible
          export ANSIBLE_FORCE_COLOR=1
          ansible-playbook -i hosts --vault-password-file vault-pass actions-playbooks/ansible-pipeline-runner.yml

      - name: Cleanup
        if: always()
        run: |
          cd ansible
          rm -f vault-pass