name: "Build Speedtest Docker container"

#on:
#  workflow_dispatch:
#  push:
#    branches: main
#    paths:
#      - docker/speedtest/**
#      - .github/workflows/docker-speedtest.yml
#  schedule:
#    - cron: 0 0 1 * * # 1st of every month at 00:00

jobs:
  docker:
    name: "Build container"
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set date
      run: echo "dt=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: docker/speedtest/Dockerfile
        push: true
        tags: |
          77cla77/speedtest:latest
          77cla77/speedtest:${{ env.dt }}
