name: "Terraform Plan"

on:
  workflow_dispatch:
  push:
    paths: terraform/**

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform init
        run: |
          cd terraform
          terraform init

      - name: Terraform plan
        run: |
          cd terraform
          terraform plan -var 'pm_api_url=${{ secrets.PM_API_URL }}' -var 'pm_user=${{ secrets.PM_USER }}' -var 'pm_password=${{ secrets.PM_PASSWORD }}'
